name: CI

# We can specify which Github events will trigger a CI build
on: [push, pull_request]

# now define a single job 'build' (but could define more)
jobs:

  build:

    # we can also specify the OS to run tests on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8]

    # a job is a seq of steps
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: |
        conda install --yes conda-build
        conda env create -n testsuite -f env.yml
        conda develop -n testsuite .
     

    - name: Test with PyTest
      run: |
        conda run -n testsuite pytest --cov=inflammation.models tests/test_models.py
