name: CI

# We can specify which Github events will trigger a CI build
on: [push, pull_request]

# now define a single job 'build' (but could define more)
jobs:

  build:

    # we can also specify the OS to run tests on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#        os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        python-version: [3.7, 3.8]

    # a job is a seq of steps
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Download Miniconda for OSX
      if: matrix.os == 'macos-latest'
      run: |
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh

    - name: Download Miniconda for linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh

    - name: Install Conda Dependencies
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: |
        bash miniconda.sh -b -p $HOME/miniconda
        source "$HOME/miniconda/etc/profile.d/conda.sh"
        conda init bash
        conda install --yes conda-build
        conda env create -n testsuite -f env.yml
        conda activate testsuite
        conda develop .
     

    - name: Test with PyTest
      run: |
        conda activate testsuite
        pytest --cov=inflammation.models tests/test_models.py
